# Generated by Django 3.0.7 on 2021-02-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dated_post',
            new_name='date_posted',
        ),
    ]
